### ISSUE TITLE
Implement other Interface Kit modal variations

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [heroku/react-hk-components#11]
See https://github.com/heroku/react-hk-components/pull/8#issuecomment-362443645

**Comment by mginnard** [comment]
Great question. For flexibility, and to handle a variety of use cases, if you're using any of these variations, you should have the ability to:
+ Show or hide any button.
+ Change the label text for any of the buttons.

**Comment by fivetanley** [comment]
closing this due to staleness
