### ISSUE TITLE
Modal rendering broken in Firefox

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [heroku/react-hk-components#14]
See https://github.com/heroku/react-hk-components/pull/8#issuecomment-362720186

**Comment by uhoh-itsmaciek** [comment]
@mginnard oh did 85f45243adedfe229de6bea60bb4099763c17ee0 fix this?

**Comment by mginnard** [comment]
It should have. Is it still broken?

**Comment by uhoh-itsmaciek** [comment]
To the react-hk-components-mobile! https://react-hk-components.herokuapp.com

**Comment by uhoh-itsmaciek** [comment]
Nope, thanks!
